use winit::event::*;

#[derive(Debug, PartialEq)]
pub enum KeyboardKeyState {
    Pressed,
    Released,
}

#[derive(Debug)]
pub enum KeyboardKey {
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Snapshot,
    Scroll,
    Pause,
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    Left,
    Up,
    Right,
    Down,
    Back,
    Return,
    Space,
    Compose,
    Caret,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,
    NavigateForward,
    NavigateBackward,
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

impl From<&VirtualKeyCode> for KeyboardKey {
    fn from(virtual_key_code: &VirtualKeyCode) -> Self {
        match virtual_key_code {
            VirtualKeyCode::Key1 => KeyboardKey::Key1,
            VirtualKeyCode::Key2 => KeyboardKey::Key2,
            VirtualKeyCode::Key3 => KeyboardKey::Key3,
            VirtualKeyCode::Key4 => KeyboardKey::Key4,
            VirtualKeyCode::Key5 => KeyboardKey::Key5,
            VirtualKeyCode::Key6 => KeyboardKey::Key6,
            VirtualKeyCode::Key7 => KeyboardKey::Key7,
            VirtualKeyCode::Key8 => KeyboardKey::Key8,
            VirtualKeyCode::Key9 => KeyboardKey::Key9,
            VirtualKeyCode::Key0 => KeyboardKey::Key0,
            VirtualKeyCode::A => KeyboardKey::A,
            VirtualKeyCode::B => KeyboardKey::B,
            VirtualKeyCode::C => KeyboardKey::C,
            VirtualKeyCode::D => KeyboardKey::D,
            VirtualKeyCode::E => KeyboardKey::E,
            VirtualKeyCode::F => KeyboardKey::F,
            VirtualKeyCode::G => KeyboardKey::G,
            VirtualKeyCode::H => KeyboardKey::H,
            VirtualKeyCode::I => KeyboardKey::I,
            VirtualKeyCode::J => KeyboardKey::J,
            VirtualKeyCode::K => KeyboardKey::K,
            VirtualKeyCode::L => KeyboardKey::L,
            VirtualKeyCode::M => KeyboardKey::M,
            VirtualKeyCode::N => KeyboardKey::N,
            VirtualKeyCode::O => KeyboardKey::O,
            VirtualKeyCode::P => KeyboardKey::P,
            VirtualKeyCode::Q => KeyboardKey::Q,
            VirtualKeyCode::R => KeyboardKey::R,
            VirtualKeyCode::S => KeyboardKey::S,
            VirtualKeyCode::T => KeyboardKey::T,
            VirtualKeyCode::U => KeyboardKey::U,
            VirtualKeyCode::V => KeyboardKey::V,
            VirtualKeyCode::W => KeyboardKey::W,
            VirtualKeyCode::X => KeyboardKey::X,
            VirtualKeyCode::Y => KeyboardKey::Y,
            VirtualKeyCode::Z => KeyboardKey::Z,
            VirtualKeyCode::Escape => KeyboardKey::Escape,
            VirtualKeyCode::F1 => KeyboardKey::F1,
            VirtualKeyCode::F2 => KeyboardKey::F2,
            VirtualKeyCode::F3 => KeyboardKey::F3,
            VirtualKeyCode::F4 => KeyboardKey::F4,
            VirtualKeyCode::F5 => KeyboardKey::F5,
            VirtualKeyCode::F6 => KeyboardKey::F6,
            VirtualKeyCode::F7 => KeyboardKey::F7,
            VirtualKeyCode::F8 => KeyboardKey::F8,
            VirtualKeyCode::F9 => KeyboardKey::F9,
            VirtualKeyCode::F10 => KeyboardKey::F10,
            VirtualKeyCode::F11 => KeyboardKey::F11,
            VirtualKeyCode::F12 => KeyboardKey::F12,
            VirtualKeyCode::F13 => KeyboardKey::F13,
            VirtualKeyCode::F14 => KeyboardKey::F14,
            VirtualKeyCode::F15 => KeyboardKey::F15,
            VirtualKeyCode::F16 => KeyboardKey::F16,
            VirtualKeyCode::F17 => KeyboardKey::F17,
            VirtualKeyCode::F18 => KeyboardKey::F18,
            VirtualKeyCode::F19 => KeyboardKey::F19,
            VirtualKeyCode::F20 => KeyboardKey::F20,
            VirtualKeyCode::F21 => KeyboardKey::F21,
            VirtualKeyCode::F22 => KeyboardKey::F22,
            VirtualKeyCode::F23 => KeyboardKey::F23,
            VirtualKeyCode::F24 => KeyboardKey::F24,
            VirtualKeyCode::Snapshot => KeyboardKey::Snapshot,
            VirtualKeyCode::Scroll => KeyboardKey::Scroll,
            VirtualKeyCode::Pause => KeyboardKey::Pause,
            VirtualKeyCode::Insert => KeyboardKey::Insert,
            VirtualKeyCode::Home => KeyboardKey::Home,
            VirtualKeyCode::Delete => KeyboardKey::Delete,
            VirtualKeyCode::End => KeyboardKey::End,
            VirtualKeyCode::PageDown => KeyboardKey::PageDown,
            VirtualKeyCode::PageUp => KeyboardKey::PageUp,
            VirtualKeyCode::Left => KeyboardKey::Left,
            VirtualKeyCode::Up => KeyboardKey::Up,
            VirtualKeyCode::Right => KeyboardKey::Right,
            VirtualKeyCode::Down => KeyboardKey::Down,
            VirtualKeyCode::Back => KeyboardKey::Back,
            VirtualKeyCode::Return => KeyboardKey::Return,
            VirtualKeyCode::Space => KeyboardKey::Space,
            VirtualKeyCode::Compose => KeyboardKey::Compose,
            VirtualKeyCode::Caret => KeyboardKey::Caret,
            VirtualKeyCode::Numlock => KeyboardKey::Numlock,
            VirtualKeyCode::Numpad0 => KeyboardKey::Numpad0,
            VirtualKeyCode::Numpad1 => KeyboardKey::Numpad1,
            VirtualKeyCode::Numpad2 => KeyboardKey::Numpad2,
            VirtualKeyCode::Numpad3 => KeyboardKey::Numpad3,
            VirtualKeyCode::Numpad4 => KeyboardKey::Numpad4,
            VirtualKeyCode::Numpad5 => KeyboardKey::Numpad5,
            VirtualKeyCode::Numpad6 => KeyboardKey::Numpad6,
            VirtualKeyCode::Numpad7 => KeyboardKey::Numpad7,
            VirtualKeyCode::Numpad8 => KeyboardKey::Numpad8,
            VirtualKeyCode::Numpad9 => KeyboardKey::Numpad9,
            VirtualKeyCode::AbntC1 => KeyboardKey::AbntC1,
            VirtualKeyCode::AbntC2 => KeyboardKey::AbntC2,
            VirtualKeyCode::Add => KeyboardKey::Add,
            VirtualKeyCode::Apostrophe => KeyboardKey::Apostrophe,
            VirtualKeyCode::Apps => KeyboardKey::Apps,
            VirtualKeyCode::At => KeyboardKey::At,
            VirtualKeyCode::Ax => KeyboardKey::Ax,
            VirtualKeyCode::Backslash => KeyboardKey::Backslash,
            VirtualKeyCode::Calculator => KeyboardKey::Calculator,
            VirtualKeyCode::Capital => KeyboardKey::Capital,
            VirtualKeyCode::Colon => KeyboardKey::Colon,
            VirtualKeyCode::Comma => KeyboardKey::Comma,
            VirtualKeyCode::Convert => KeyboardKey::Convert,
            VirtualKeyCode::Decimal => KeyboardKey::Decimal,
            VirtualKeyCode::Divide => KeyboardKey::Divide,
            VirtualKeyCode::Equals => KeyboardKey::Equals,
            VirtualKeyCode::Grave => KeyboardKey::Grave,
            VirtualKeyCode::Kana => KeyboardKey::Kana,
            VirtualKeyCode::Kanji => KeyboardKey::Kanji,
            VirtualKeyCode::LAlt => KeyboardKey::LAlt,
            VirtualKeyCode::LBracket => KeyboardKey::LBracket,
            VirtualKeyCode::LControl => KeyboardKey::LControl,
            VirtualKeyCode::LShift => KeyboardKey::LShift,
            VirtualKeyCode::LWin => KeyboardKey::LWin,
            VirtualKeyCode::Mail => KeyboardKey::Mail,
            VirtualKeyCode::MediaSelect => KeyboardKey::MediaSelect,
            VirtualKeyCode::MediaStop => KeyboardKey::MediaStop,
            VirtualKeyCode::Minus => KeyboardKey::Minus,
            VirtualKeyCode::Multiply => KeyboardKey::Multiply,
            VirtualKeyCode::Mute => KeyboardKey::Mute,
            VirtualKeyCode::MyComputer => KeyboardKey::MyComputer,
            VirtualKeyCode::NavigateForward => KeyboardKey::NavigateForward,
            VirtualKeyCode::NavigateBackward => KeyboardKey::NavigateBackward,
            VirtualKeyCode::NextTrack => KeyboardKey::NextTrack,
            VirtualKeyCode::NoConvert => KeyboardKey::NoConvert,
            VirtualKeyCode::NumpadComma => KeyboardKey::NumpadComma,
            VirtualKeyCode::NumpadEnter => KeyboardKey::NumpadEnter,
            VirtualKeyCode::NumpadEquals => KeyboardKey::NumpadEquals,
            VirtualKeyCode::OEM102 => KeyboardKey::OEM102,
            VirtualKeyCode::Period => KeyboardKey::Period,
            VirtualKeyCode::PlayPause => KeyboardKey::PlayPause,
            VirtualKeyCode::Power => KeyboardKey::Power,
            VirtualKeyCode::PrevTrack => KeyboardKey::PrevTrack,
            VirtualKeyCode::RAlt => KeyboardKey::RAlt,
            VirtualKeyCode::RBracket => KeyboardKey::RBracket,
            VirtualKeyCode::RControl => KeyboardKey::RControl,
            VirtualKeyCode::RShift => KeyboardKey::RShift,
            VirtualKeyCode::RWin => KeyboardKey::RWin,
            VirtualKeyCode::Semicolon => KeyboardKey::Semicolon,
            VirtualKeyCode::Slash => KeyboardKey::Slash,
            VirtualKeyCode::Sleep => KeyboardKey::Sleep,
            VirtualKeyCode::Stop => KeyboardKey::Stop,
            VirtualKeyCode::Subtract => KeyboardKey::Subtract,
            VirtualKeyCode::Sysrq => KeyboardKey::Sysrq,
            VirtualKeyCode::Tab => KeyboardKey::Tab,
            VirtualKeyCode::Underline => KeyboardKey::Underline,
            VirtualKeyCode::Unlabeled => KeyboardKey::Unlabeled,
            VirtualKeyCode::VolumeDown => KeyboardKey::VolumeDown,
            VirtualKeyCode::VolumeUp => KeyboardKey::VolumeUp,
            VirtualKeyCode::Wake => KeyboardKey::Wake,
            VirtualKeyCode::WebBack => KeyboardKey::WebBack,
            VirtualKeyCode::WebFavorites => KeyboardKey::WebFavorites,
            VirtualKeyCode::WebForward => KeyboardKey::WebForward,
            VirtualKeyCode::WebHome => KeyboardKey::WebHome,
            VirtualKeyCode::WebRefresh => KeyboardKey::WebRefresh,
            VirtualKeyCode::WebSearch => KeyboardKey::WebSearch,
            VirtualKeyCode::WebStop => KeyboardKey::WebStop,
            VirtualKeyCode::Yen => KeyboardKey::Yen,
            VirtualKeyCode::Copy => KeyboardKey::Copy,
            VirtualKeyCode::Paste => KeyboardKey::Paste,
            VirtualKeyCode::Cut => KeyboardKey::Cut,
        }
    }
}

impl From<&ElementState> for KeyboardKeyState {
    fn from(element_state: &ElementState) -> Self {
        match element_state {
            ElementState::Pressed => KeyboardKeyState::Pressed,
            ElementState::Released => KeyboardKeyState::Released,
        }
    }
}

#[derive(Debug)]
pub struct KeyboardInput {
    pub key: KeyboardKey,
    pub state: KeyboardKeyState,
}

impl KeyboardInput {
    pub fn new(key: &VirtualKeyCode, state: &ElementState) -> Self {
        let key = KeyboardKey::from(key);
        let state = KeyboardKeyState::from(state);
        Self { key, state }
    }
}
